### ISSUE TITLE
This website sucks.

### ISSUE THREAD

**Issue by Mega-Mewthree** [Moeplhausen/SunknightsWebsite#4]
Use better security and ratelimits. lol also posting your full code on github is not the best idea. Just helps us find vulns.

**Comment by Moeplhausen** [comment]
If you find any "vulns", you are free to report them.

Ratelimits should be done on a lower level (webserver, firewall, etc).

Also reports from script kiddies who try to ddos sites with their slow home internet (lol) + having an open port to their router login (lollol) cannot be taken seriously.
